name: run-BTC-MACD-Script

on:
  schedule:
    - cron: '0 5 * * *'

jobs:
  run-BTC-MACD-Script:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - run: pip install -r ./BTC_MACD/requirements.txt
      - name: Run Scripts
        env:
          user_name: ${{ secrets.USER_NAME }}
          password: ${{ secrets.PASSWORD }}
          totp_key: ${{ secrets.TOTP_KEY }}
        run: |
          python ./main.py
